### ISSUE TITLE
Hangs at startup if first table needs apostrophes to be addressed

### ISSUE THREAD

**Issue by Nemecsek** [plotly/falcon#468] opened 2018-06-27 07:14 UTC
FalconSQL (Linux v.2.4.0) creates a first query in the query panel at startup, such as `SELECT * FROM first-table LIMIT 1000`.

The issue is related to this first table name: if it needs apostrophes to be addressed in common SQL queries (such as in \` `aa-first-table` `) the program stops working and it is not possible to select any other table nor change the query.

To try, create a table aa-first-table and connect.
A possible workaround is to create a first table that doesn't need apostrophes to be addresses (such as `a`).

**Comment by n-riesco** [comment] 2018-06-27 07:55
Thank you for the report (and the workaround!).

We have a number of bugs caused by a poor handling of request errors in UI. I've opened issue #469 to keep track of them.

**Comment by Nemecsek** [comment] 2018-06-27 08:57
At least in this case the solution should be easy: to avoid the creation of the first "demo" query that's executed automatically at start. What is it its use, anyway?

**Comment by n-riesco** [comment] 2018-08-24 14:02
Closing in favour of #264

**Closed by n-riesco** 2018-08-24 14:02 UTC
Labels: bug
